#!/usr/bin/env python3
"""
Generate 800 Bible trivia questions covering 16 combinations of
4 difficulty levels x 4 categories, with exactly 50 questions per combination.

Output: /home/z/my-project/prisma/trivia-questions.json

Each question is a JSON object with fields:
  questionId, question, options (4), correctAnswer (index 0-3),
  explanation, scriptureReference, difficulty, category, basePoints,
  bibleBook, topic
"""

import json
import os
import hashlib
import random
from collections import Counter

# --- Configuration ---------------------------------------------------------

DIFFICULTY_PREFIX = {
    "beginners": "beg",
    "intermediate": "int",
    "skilled": "skl",
    "expert": "exp",
}

CATEGORY_PREFIX = {
    "full_bible": "fb",
    "new_testament": "nt",
    "old_testament": "ot",
    "apologetics": "ap",
}

DIFFICULTY_POINTS = {
    "beginners": 10,
    "intermediate": 20,
    "skilled": 30,
    "expert": 50,
}

DIFFICULTIES = ["beginners", "intermediate", "skilled", "expert"]
CATEGORIES = ["full_bible", "new_testament", "old_testament", "apologetics"]


# --- Question Data ---------------------------------------------------------
# Each question is a tuple:
# (question, [opt1, opt2, opt3, opt4], correct_value, explanation,
#  scripture_reference, bible_book_or_None, topic)
#
# The script will shuffle options deterministically so the correct answer
# position varies across questions.

QUESTIONS = {}


# ===========================================================================
# BEGINNERS (10 FP)
# ===========================================================================

# -- Beginners / Full Bible (50) --------------------------------------------
QUESTIONS[("beginners", "full_bible")] = [
    ("Who created the heavens and the earth?",
     ["Adam", "Noah", "God", "Moses"], "God",
     "Genesis 1:1 - In the beginning God created the heavens and the earth.",
     "Genesis 1:1", "Genesis", "Creation"),
    ("Who was the first man?",
     ["Abraham", "Adam", "Noah", "David"], "Adam",
     "Genesis 2:7 - The Lord God formed man from the dust of the ground.",
     "Genesis 2:7", "Genesis", "Creation"),
    ("Who was the first woman?",
     ["Sarah", "Rachel", "Eve", "Leah"], "Eve",
     "Genesis 2:22 - God made a woman from the rib he had taken out of the man.",
     "Genesis 2:22", "Genesis", "Creation"),
    ("Who built the ark?",
     ["Abraham", "Moses", "Noah", "David"], "Noah",
     "Genesis 6:14 - Make yourself an ark of cypress wood.",
     "Genesis 6:14", "Genesis", "Flood"),
    ("How many days did God take to create the world?",
     ["5", "6", "7", "10"], "6",
     "Genesis 2:2 - By the seventh day God had finished the work he had been doing.",
     "Genesis 2:2", "Genesis", "Creation"),
    ("What did God create on the first day?",
     ["Animals", "Light", "Stars", "Water"], "Light",
     "Genesis 1:3 - God said, 'Let there be light,' and there was light.",
     "Genesis 1:3", "Genesis", "Creation"),
    ("How many days did it rain during the flood?",
     ["30", "40", "50", "100"], "40",
     "Genesis 7:12 - The rain fell on the earth forty days and forty nights.",
     "Genesis 7:12", "Genesis", "Flood"),
    ("What sign did God give as a promise after the flood?",
     ["A cloud", "A rainbow", "The sun", "A star"], "A rainbow",
     "Genesis 9:13 - I have set my rainbow in the clouds as a covenant.",
     "Genesis 9:13", "Genesis", "Covenant"),
    ("Who was called the father of many nations?",
     ["Moses", "David", "Abraham", "Isaac"], "Abraham",
     "Genesis 17:5 - Your name will be Abraham, for I have made you a father of many nations.",
     "Genesis 17:5", "Genesis", "Patriarchs"),
    ("Who led the Israelites out of Egypt?",
     ["Aaron", "Moses", "Joshua", "David"], "Moses",
     "Exodus 12:37 - The Israelites journeyed from Rameses to Succoth under Moses.",
     "Exodus 12:37", "Exodus", "Exodus"),
    ("What did God give Moses on Mount Sinai?",
     ["The Ark of the Covenant", "The Ten Commandments", "Manna", "A staff"], "The Ten Commandments",
     "Exodus 31:18 - God gave Moses the tablets of the covenant law inscribed by the finger of God.",
     "Exodus 31:18", "Exodus", "Law"),
    ("Who parted the Red Sea?",
     ["Joshua", "Aaron", "Moses", "Elijah"], "Moses",
     "Exodus 14:21 - Moses stretched out his hand over the sea, and the Lord divided it.",
     "Exodus 14:21", "Exodus", "Exodus"),
    ("Who was thrown into the lions' den?",
     ["Daniel", "David", "Elijah", "Joseph"], "Daniel",
     "Daniel 6:16 - Daniel was brought and thrown into the den of lions.",
     "Daniel 6:16", "Daniel", "Faith"),
    ("Who killed Goliath?",
     ["Saul", "Jonathan", "David", "Samuel"], "David",
     "1 Samuel 17:50 - David triumphed over the Philistine with a sling and a stone.",
     "1 Samuel 17:50", "1 Samuel", "David"),
    ("Who was swallowed by a great fish?",
     ["Jonah", "Peter", "Paul", "Isaiah"], "Jonah",
     "Jonah 1:17 - The Lord provided a huge fish to swallow Jonah, and he was inside three days.",
     "Jonah 1:17", "Jonah", "Prophets"),
    ("Where was Jesus born?",
     ["Nazareth", "Bethlehem", "Jerusalem", "Capernaum"], "Bethlehem",
     "Matthew 2:1 - Jesus was born in Bethlehem of Judea.",
     "Matthew 2:1", "Matthew", "Jesus Life"),
    ("Who was Jesus' mother?",
     ["Martha", "Mary", "Elizabeth", "Anna"], "Mary",
     "Luke 1:27 - God sent the angel to a virgin named Mary.",
     "Luke 1:27", "Luke", "Jesus Life"),
    ("Who was Jesus' earthly father?",
     ["Joseph", "Zechariah", "Simeon", "Joachim"], "Joseph",
     "Matthew 1:16 - Joseph was the husband of Mary, the mother of Jesus.",
     "Matthew 1:16", "Matthew", "Jesus Life"),
    ("Who baptized Jesus?",
     ["Peter", "John the Baptist", "Andrew", "Philip"], "John the Baptist",
     "Matthew 3:13 - Jesus came from Galilee to the Jordan to be baptized by John.",
     "Matthew 3:13", "Matthew", "Jesus Life"),
    ("What river was Jesus baptized in?",
     ["The Nile", "The Jordan", "The Tigris", "The Euphrates"], "The Jordan",
     "Matthew 3:13 - Jesus came to the Jordan to be baptized by John.",
     "Matthew 3:13", "Matthew", "Jesus Life"),
    ("How many days was Jesus tempted in the wilderness?",
     ["20", "30", "40", "50"], "40",
     "Matthew 4:2 - After fasting forty days and forty nights, he was hungry.",
     "Matthew 4:2", "Matthew", "Jesus Life"),
    ("How many apostles did Jesus choose?",
     ["7", "10", "12", "24"], "12",
     "Matthew 10:1 - Jesus called his twelve disciples to him and gave them authority.",
     "Matthew 10:1", "Matthew", "Disciples"),
    ("Who betrayed Jesus?",
     ["Peter", "Judas Iscariot", "Thomas", "James"], "Judas Iscariot",
     "Matthew 26:14 - Judas Iscariot went to the chief priests to betray Jesus.",
     "Matthew 26:14", "Matthew", "Jesus Passion"),
    ("Who denied Jesus three times?",
     ["John", "Peter", "Andrew", "Judas"], "Peter",
     "Luke 22:54-62 - Peter denied Jesus three times before the rooster crowed.",
     "Luke 22:54", "Luke", "Jesus Passion"),
    ("What did Jesus use to feed 5,000 people?",
     ["7 loaves and 2 fish", "5 loaves and 2 fish", "3 loaves and 5 fish", "10 loaves and 1 fish"], "5 loaves and 2 fish",
     "Matthew 14:17 - We have here only five loaves of bread and two fish.",
     "Matthew 14:17", "Matthew", "Jesus Miracles"),
    ("What was Jesus' first recorded miracle?",
     ["Healing a leper", "Turning water into wine", "Feeding 5000", "Walking on water"], "Turning water into wine",
     "John 2:11 - This, the first of his signs, Jesus did at Cana in Galilee.",
     "John 2:11", "John", "Jesus Miracles"),
    ("Who walked on water toward Jesus?",
     ["John", "Peter", "James", "Andrew"], "Peter",
     "Matthew 14:29 - Peter got out of the boat, walked on the water, and came toward Jesus.",
     "Matthew 14:29", "Matthew", "Jesus Miracles"),
    ("On what day did Jesus rise from the dead?",
     ["The first day", "The second day", "The third day", "The seventh day"], "The third day",
     "1 Corinthians 15:4 - He was raised on the third day according to the Scriptures.",
     "1 Corinthians 15:4", "1 Corinthians", "Resurrection"),
    ("Who rolled the stone away from Jesus' tomb?",
     ["Peter", "An angel", "Roman guards", "Mary"], "An angel",
     "Matthew 28:2 - An angel of the Lord came down and rolled back the stone.",
     "Matthew 28:2", "Matthew", "Resurrection"),
    ("What does the name 'Emmanuel' mean?",
     ["God is great", "God with us", "God saves", "God hears"], "God with us",
     "Matthew 1:23 - They will call him Emmanuel, which means 'God with us.'",
     "Matthew 1:23", "Matthew", "Prophecy"),
    ("How many books are in the Bible?",
     ["55", "66", "77", "88"], "66",
     "2 Timothy 3:16 - All Scripture is God-breathed. The Bible has 66 books (39 OT, 27 NT).",
     "2 Timothy 3:16", None, "Bible Facts"),
    ("How many books are in the Old Testament?",
     ["27", "33", "39", "46"], "39",
     "Luke 24:44 - The Protestant Old Testament has 39 books.",
     "Luke 24:44", None, "Bible Facts"),
    ("How many books are in the New Testament?",
     ["21", "27", "33", "39"], "27",
     "Revelation 22:18 - The New Testament has 27 books, from Matthew to Revelation.",
     "Revelation 22:18", None, "Bible Facts"),
    ("What is the first book of the Bible?",
     ["Exodus", "Genesis", "Leviticus", "Matthew"], "Genesis",
     "Genesis 1:1 - Genesis means 'beginnings' and is the first book of the Bible.",
     "Genesis 1:1", "Genesis", "Bible Facts"),
    ("What is the last book of the Bible?",
     ["Acts", "Jude", "Revelation", "Malachi"], "Revelation",
     "Revelation 22:21 - Revelation, written by John, is the last book of the Bible.",
     "Revelation 22:21", "Revelation", "Bible Facts"),
    ("What is the shortest verse in the Bible?",
     ["'God is love'", "'Jesus wept'", "'Rejoice always'", "'Pray continually'"], "'Jesus wept'",
     "John 11:35 - 'Jesus wept' is the shortest verse in the English Bible.",
     "John 11:35", "John", "Bible Facts"),
    ("What did God create on the second day?",
     ["Light", "The sky (firmament)", "Land", "The sun"], "The sky (firmament)",
     "Genesis 1:6-8 - God made the vault (firmament) and separated the waters.",
     "Genesis 1:6", "Genesis", "Creation"),
    ("Who was the first murderer?",
     ["Cain", "Abel", "Seth", "Lamech"], "Cain",
     "Genesis 4:8 - Cain attacked his brother Abel and killed him.",
     "Genesis 4:8", "Genesis", "Early History"),
    ("How many of each clean animal did Noah take on the ark?",
     ["One pair", "Two pairs", "Seven pairs", "Ten pairs"], "Seven pairs",
     "Genesis 7:2 - Take with you seven pairs of every kind of clean animal.",
     "Genesis 7:2", "Genesis", "Flood"),
    ("What did God promise to make Abraham into?",
     ["A wealthy nation", "A great nation", "A mighty army", "A royal palace"], "A great nation",
     "Genesis 12:2 - I will make you into a great nation and I will bless you.",
     "Genesis 12:2", "Genesis", "Patriarchs"),
    ("On what did God write the Ten Commandments?",
     ["Papyrus", "Stone tablets", "A scroll", "Wood"], "Stone tablets",
     "Exodus 31:18 - God gave Moses the tablets of stone inscribed by the finger of God.",
     "Exodus 31:18", "Exodus", "Law"),
    ("How many years did the Israelites wander in the wilderness?",
     ["20", "30", "40", "70"], "40",
     "Numbers 14:33 - Your children will be shepherds here for forty years.",
     "Numbers 14:33", "Numbers", "Exodus"),
    ("Who succeeded Moses as leader of Israel?",
     ["Aaron", "Joshua", "Caleb", "Samuel"], "Joshua",
     "Deuteronomy 34:9 - Joshua son of Nun was filled with the spirit of wisdom.",
     "Deuteronomy 34:9", "Deuteronomy", "Conquest"),
    ("Who was the giant that David fought?",
     ["Saul", "Goliath", "Og", "Sisera"], "Goliath",
     "1 Samuel 17:4 - A champion named Goliath, who was from Gath, came out of the Philistine camp.",
     "1 Samuel 17:4", "1 Samuel", "David"),
    ("Who were thrown into the fiery furnace?",
     ["Daniel alone", "Shadrach, Meshach, Abednego", "Elijah and Elisha", "Three prophets"], "Shadrach, Meshach, Abednego",
     "Daniel 3:6 - Whoever does not worship the image will be thrown into the blazing furnace.",
     "Daniel 3:6", "Daniel", "Faith"),
    ("What did Jesus do at the Last Supper?",
     ["Washed the disciples' feet and shared a meal", "Healed the sick", "Preached a sermon", "Prayed all night"], "Washed the disciples' feet and shared a meal",
     "John 13:5 - Jesus poured water into a basin and began to wash his disciples' feet.",
     "John 13:5", "John", "Jesus Passion"),
    ("Where was Jesus crucified?",
     ["Bethlehem", "Golgotha", "Nazareth", "Capernaum"], "Golgotha",
     "John 19:17 - He went out to the place of the Skull (Golgotha).",
     "John 19:17", "John", "Jesus Passion"),
    ("What is the Golden Rule?",
     ["Do to others as you would have them do to you", "An eye for an eye", "Love your enemies", "Turn the other cheek"], "Do to others as you would have them do to you",
     "Matthew 7:12 - So in everything, do to others what you would have them do to you.",
     "Matthew 7:12", "Matthew", "Teachings of Jesus"),
    ("Who was John the Baptist's father?",
     ["Joseph", "Zechariah", "Simeon", "Eli"], "Zechariah",
     "Luke 1:13 - Your wife Elizabeth will bear you a son; you are to call him John.",
     "Luke 1:13", "Luke", "John the Baptist"),
    ("What did the dove bring back to Noah after the flood?",
     ["A leaf", "An olive branch", "A worm", "A flower"], "An olive branch",
     "Genesis 8:11 - The dove returned with a freshly plucked olive leaf in its beak.",
     "Genesis 8:11", "Genesis", "Flood"),
]


# -- Beginners / New Testament (50) -----------------------------------------
QUESTIONS[("beginners", "new_testament")] = [
    ("Who were the parents of John the Baptist?",
     ["Mary and Joseph", "Zechariah and Elizabeth", "Simeon and Anna", "Anna and Joachim"], "Zechariah and Elizabeth",
     "Luke 1:5-13 - Zechariah and Elizabeth were righteous before God; the angel promised them a son.",
     "Luke 1:13", "Luke", "John the Baptist"),
    ("What was John the Baptist's food?",
     ["Bread and water", "Locusts and wild honey", "Fish and bread", "Manna"], "Locusts and wild honey",
     "Matthew 3:4 - John's food was locusts and wild honey.",
     "Matthew 3:4", "Matthew", "John the Baptist"),
    ("What did John the Baptist wear?",
     ["Silk robes", "Camel's hair", "Linen", "Wool"], "Camel's hair",
     "Matthew 3:4 - John wore clothing made of camel's hair, with a leather belt.",
     "Matthew 3:4", "Matthew", "John the Baptist"),
    ("Which angel announced Jesus' birth to Mary?",
     ["Michael", "Gabriel", "Raphael", "Uriel"], "Gabriel",
     "Luke 1:26-27 - God sent the angel Gabriel to Nazareth, to a virgin named Mary.",
     "Luke 1:26", "Luke", "Jesus Life"),
    ("Who appeared to the shepherds when Jesus was born?",
     ["A prophet", "Angels", "Wise men", "King Herod"], "Angels",
     "Luke 2:9 - An angel of the Lord appeared to the shepherds, and a great company of angels.",
     "Luke 2:9", "Luke", "Jesus Life"),
    ("Who brought gifts of gold, frankincense, and myrrh to Jesus?",
     ["Shepherds", "The Magi (Wise Men)", "King Herod", "Simeon"], "The Magi (Wise Men)",
     "Matthew 2:11 - The Magi opened their treasures and presented him with gifts.",
     "Matthew 2:11", "Matthew", "Jesus Life"),
    ("Where did Jesus' family flee to escape King Herod?",
     ["Egypt", "Syria", "Greece", "Persia"], "Egypt",
     "Matthew 2:13-14 - Joseph took the child and his mother by night and escaped to Egypt.",
     "Matthew 2:13", "Matthew", "Jesus Life"),
    ("In which town did Jesus grow up?",
     ["Bethlehem", "Nazareth", "Jerusalem", "Capernaum"], "Nazareth",
     "Matthew 2:23 - He went and lived in a town called Nazareth.",
     "Matthew 2:23", "Matthew", "Jesus Life"),
    ("At what age was Jesus found teaching in the temple?",
     ["8 years old", "10 years old", "12 years old", "18 years old"], "12 years old",
     "Luke 2:42 - When Jesus was twelve years old, they went up to the festival.",
     "Luke 2:42", "Luke", "Jesus Life"),
    ("What descended on Jesus at his baptism?",
     ["A cloud", "A dove", "Fire", "Lightning"], "A dove",
     "Matthew 3:16 - The Spirit of God descending like a dove.",
     "Matthew 3:16", "Matthew", "Jesus Life"),
    ("What did God the Father say at Jesus' baptism?",
     ["'This is my beloved Son'", "'Behold the Lamb of God'", "'Follow him'", "'He is the Messiah'"], "'This is my beloved Son'",
     "Matthew 3:17 - A voice from heaven said, 'This is my Son, whom I love.'",
     "Matthew 3:17", "Matthew", "Jesus Life"),
    ("Who tempted Jesus in the wilderness?",
     ["A Pharisee", "Satan", "A demon", "Herod"], "Satan",
     "Matthew 4:1 - Jesus was led by the Spirit into the wilderness to be tempted by the devil.",
     "Matthew 4:1", "Matthew", "Jesus Life"),
    ("Who were the first two disciples Jesus called?",
     ["Peter and John", "Peter and Andrew", "James and John", "Philip and Nathanael"], "Peter and Andrew",
     "Matthew 4:18-20 - Jesus called Peter and Andrew, who were casting a net into the lake.",
     "Matthew 4:18", "Matthew", "Disciples"),
    ("What was Peter's original name?",
     ["Simon", "Simeon", "Saul", "Bartholomew"], "Simon",
     "John 1:42 - Jesus said, 'You are Simon son of John. You will be called Cephas (Peter).'",
     "John 1:42", "John", "Disciples"),
    ("Who was Peter's brother?",
     ["Andrew", "John", "James", "Philip"], "Andrew",
     "John 1:40 - Andrew, Simon Peter's brother, was one of the two who heard John.",
     "John 1:40", "John", "Disciples"),
    ("Who was the father of James and John?",
     ["Zebedee", "Alphaeus", "Jonah", "Joseph"], "Zebedee",
     "Matthew 4:21 - James son of Zebedee and his brother John.",
     "Matthew 4:21", "Matthew", "Disciples"),
    ("What nickname did Jesus give James and John?",
     ["Sons of Thunder", "Sons of Peace", "Sons of Light", "Sons of David"], "Sons of Thunder",
     "Mark 3:17 - Jesus named them Boanerges, which means 'Sons of Thunder.'",
     "Mark 3:17", "Mark", "Disciples"),
    ("Which disciple was a tax collector before following Jesus?",
     ["Matthew", "Thomas", "Bartholomew", "Thaddaeus"], "Matthew",
     "Matthew 9:9 - Jesus saw a man named Matthew sitting at the tax collector's booth.",
     "Matthew 9:9", "Matthew", "Disciples"),
    ("Which disciple doubted Jesus' resurrection at first?",
     ["Thomas", "Philip", "Andrew", "James"], "Thomas",
     "John 20:24-25 - Thomas said, 'Unless I see the nail marks, I will not believe.'",
     "John 20:24", "John", "Resurrection"),
    ("Who replaced Judas Iscariot as the twelfth apostle?",
     ["Barnabas", "Matthias", "Stephen", "Philip"], "Matthias",
     "Acts 1:26 - They cast lots, and the lot fell to Matthias.",
     "Acts 1:26", "Acts", "Disciples"),
    ("Who anointed Jesus' feet with expensive perfume?",
     ["Martha", "Mary (sister of Martha)", "Mary Magdalene", "Joanna"], "Mary (sister of Martha)",
     "John 12:3 - Mary took expensive perfume and poured it on Jesus' feet.",
     "John 12:3", "John", "Jesus Life"),
    ("Who carried Jesus' cross to Calvary?",
     ["Simon Peter", "Simon of Cyrene", "Joseph of Arimathea", "John"], "Simon of Cyrene",
     "Matthew 27:32 - They forced Simon of Cyrene to carry the cross.",
     "Matthew 27:32", "Matthew", "Jesus Passion"),
    ("Who asked Pilate for Jesus' body for burial?",
     ["Joseph of Arimathea", "Nicodemus", "Peter", "John"], "Joseph of Arimathea",
     "Matthew 27:57-58 - Joseph of Arimathea asked Pilate for Jesus' body.",
     "Matthew 27:57", "Matthew", "Jesus Passion"),
    ("Who was the first person to see the risen Jesus?",
     ["Peter", "Mary Magdalene", "John", "Thomas"], "Mary Magdalene",
     "John 20:16 - Jesus said to her, 'Mary.' She turned and cried, 'Rabboni!'",
     "John 20:16", "John", "Resurrection"),
    ("How many pieces of silver did Judas receive for betraying Jesus?",
     ["20", "30", "40", "50"], "30",
     "Matthew 26:15 - They counted out for him thirty pieces of silver.",
     "Matthew 26:15", "Matthew", "Jesus Passion"),
    ("Who was the Roman governor who tried Jesus?",
     ["Pontius Pilate", "Herod Antipas", "Caesar Augustus", "Felix"], "Pontius Pilate",
     "Matthew 27:2 - They bound Jesus, led him away, and handed him over to Pilate the governor.",
     "Matthew 27:2", "Matthew", "Jesus Passion"),
    ("Who was the high priest who questioned Jesus?",
     ["Annas", "Caiaphas", "Ananias", "Gamaliel"], "Caiaphas",
     "Matthew 26:57 - They took Jesus to the house of Caiaphas, the high priest.",
     "Matthew 26:57", "Matthew", "Jesus Passion"),
    ("What was placed on Jesus' head during the crucifixion?",
     ["A golden crown", "A crown of thorns", "A purple robe", "A wreath of laurel"], "A crown of thorns",
     "Matthew 27:29 - They twisted together a crown of thorns and set it on his head.",
     "Matthew 27:29", "Matthew", "Jesus Passion"),
    ("What were Jesus' final words on the cross, according to John?",
     ["'My God, why?'", "'It is finished'", "'Father, forgive them'", "'Into your hands'"], "'It is finished'",
     "John 19:30 - Jesus said, 'It is finished,' and bowed his head and gave up his spirit.",
     "John 19:30", "John", "Jesus Passion"),
    ("What happened to the temple veil when Jesus died?",
     ["It was torn in two", "It caught fire", "It turned to gold", "It was stolen"], "It was torn in two",
     "Matthew 27:51 - The curtain of the temple was torn in two from top to bottom.",
     "Matthew 27:51", "Matthew", "Jesus Passion"),
    ("What did the centurion say when Jesus died?",
     ["'This man was a sinner'", "'Surely this was the Son of God'", "'Crucify him!'", "'Hail, King of the Jews'"], "'Surely this was the Son of God'",
     "Matthew 27:54 - The centurion said, 'Surely he was the Son of God!'",
     "Matthew 27:54", "Matthew", "Jesus Passion"),
    ("How many days did Jesus appear to his disciples after his resurrection?",
     ["10", "20", "40", "50"], "40",
     "Acts 1:3 - After his suffering, he presented himself to them over forty days.",
     "Acts 1:3", "Acts", "Resurrection"),
    ("From which mountain did Jesus ascend to heaven?",
     ["Mount Sinai", "Mount of Olives", "Mount Hermon", "Mount Tabor"], "Mount of Olives",
     "Acts 1:12 - They returned to Jerusalem from the hill called the Mount of Olives.",
     "Acts 1:12", "Acts", "Ascension"),
    ("What did Jesus promise to send after his ascension?",
     ["Angels", "The Holy Spirit", "Prophets", "A king"], "The Holy Spirit",
     "John 14:26 - The Father will send the Holy Spirit in my name.",
     "John 14:26", "John", "Holy Spirit"),
    ("What event marked the coming of the Holy Spirit on the disciples?",
     ["Pentecost", "Passover", "Tabernacles", "Trumpets"], "Pentecost",
     "Acts 2:1-4 - When the day of Pentecost came, they were all filled with the Holy Spirit.",
     "Acts 2:1", "Acts", "Holy Spirit"),
    ("Who was the first Christian martyr (stoned to death)?",
     ["Stephen", "James", "Paul", "Peter"], "Stephen",
     "Acts 7:59-60 - While they were stoning Stephen, he prayed, 'Lord, do not hold this sin against them.'",
     "Acts 7:59", "Acts", "Early Church"),
    ("Who was blinded on the road to Damascus?",
     ["Peter", "Saul (Paul)", "Cornelius", "Barnabas"], "Saul (Paul)",
     "Acts 9:3-9 - Saul saw a light from heaven and was blinded; he was led to Damascus.",
     "Acts 9:3", "Acts", "Paul"),
    ("What was Saul's name changed to after his conversion?",
     ["Peter", "Paul", "Silas", "Barnabas"], "Paul",
     "Acts 13:9 - Saul, who was also called Paul, filled with the Holy Spirit...",
     "Acts 13:9", "Acts", "Paul"),
    ("Who wrote the Book of Revelation?",
     ["Peter", "John", "Paul", "James"], "John",
     "Revelation 1:1 - The revelation from Jesus Christ, signified to his servant John.",
     "Revelation 1:1", "Revelation", "Revelation"),
    ("On which island was John exiled when he wrote Revelation?",
     ["Cyprus", "Patmos", "Crete", "Malta"], "Patmos",
     "Revelation 1:9 - I, John, was on the island called Patmos because of the word of God.",
     "Revelation 1:9", "Revelation", "Revelation"),
    ("Where were believers first called 'Christians'?",
     ["Jerusalem", "Antioch", "Rome", "Ephesus"], "Antioch",
     "Acts 11:26 - The disciples were called Christians first at Antioch.",
     "Acts 11:26", "Acts", "Early Church"),
    ("Which Roman centurion was converted under Peter's ministry?",
     ["Cornelius", "Julius", "Claudius", "Sergius"], "Cornelius",
     "Acts 10:1-2 - Cornelius, a centurion, was devout and God-fearing.",
     "Acts 10:1", "Acts", "Early Church"),
    ("What was Luke's profession?",
     ["A tentmaker", "A physician", "A fisherman", "A tax collector"], "A physician",
     "Colossians 4:14 - Luke, the beloved physician, greets you.",
     "Colossians 4:14", "Colossians", "Paul"),
    ("What was Matthew's other name?",
     ["Levi", "Bartholomew", "Thaddaeus", "Simon"], "Levi",
     "Mark 2:14 - As he walked along, he saw Levi son of Alphaeus sitting at the tax booth.",
     "Mark 2:14", "Mark", "Disciples"),
    ("What did Jesus say to Zacchaeus, the tax collector?",
     ["'Leave this town'", "'Today salvation has come to this house'", "'Repent and be baptized'", "'Give all you have'"], "'Today salvation has come to this house'",
     "Luke 19:9 - Jesus said, 'Today salvation has come to this house.'",
     "Luke 19:9", "Luke", "Jesus Ministry"),
    ("What did Zacchaeus climb to see Jesus?",
     ["A palm tree", "A sycamore tree", "A cedar tree", "An oak tree"], "A sycamore tree",
     "Luke 19:4 - Zacchaeus ran ahead and climbed a sycamore tree to see Jesus.",
     "Luke 19:4", "Luke", "Jesus Ministry"),
    ("Who were the two brothers Jesus called 'Sons of Thunder'?",
     ["Peter and Andrew", "James and John", "Philip and Bartholomew", "Thomas and Matthew"], "James and John",
     "Mark 3:17 - Jesus named James and John 'Boanerges,' meaning 'Sons of Thunder.'",
     "Mark 3:17", "Mark", "Disciples"),
    ("What did Jesus say he was 'the Way, the Truth, and the'?",
     ["Light", "Life", "Lord", "Love"], "Life",
     "John 14:6 - Jesus said, 'I am the way, the truth, and the life.'",
     "John 14:6", "John", "Teachings of Jesus"),
    ("Who was the prophetess who recognized baby Jesus in the temple?",
     ["Anna", "Elizabeth", "Deborah", "Huldah"], "Anna",
     "Luke 2:36-38 - Anna, a prophetess, gave thanks to God and spoke about the child Jesus.",
     "Luke 2:36", "Luke", "Jesus Life"),
    ("Who was the righteous man who blessed baby Jesus and prophesied over him?",
     ["Simeon", "Zechariah", "Joseph", "Nicodemus"], "Simeon",
     "Luke 2:25-35 - Simeon took Jesus in his arms and praised God.",
     "Luke 2:25", "Luke", "Jesus Life"),
    ("What did Jesus tell Nicodemus he must be to see the kingdom of God?",
     ["Born again", "Baptized", "Circumcised", "A priest"], "Born again",
     "John 3:3 - Jesus said, 'No one can see the kingdom of God unless they are born again.'",
     "John 3:3", "John", "Teachings of Jesus"),
    ("What is the most famous Bible verse, John 3:16, about?",
     ["God's love for the world", "The creation", "The Ten Commandments", "The end times"], "God's love for the world",
     "John 3:16 - For God so loved the world that he gave his one and only Son.",
     "John 3:16", "John", "Teachings of Jesus"),
]
