#!/usr/bin/env python3
"""Restore each language file's existing translations from git HEAD,
then merge with the new English base (filling missing keys with English).
"""
import subprocess
import re
from pathlib import Path
import json

ROOT = Path("/home/z/my-project/src/lib/i18n")
EN_FILE = ROOT / "en.ts"
LANGS = ["hi", "bn", "te", "mr", "ta", "gu", "ur", "kn", "or", "ml", "pa", "as"]

def load_strings_from_text(content: str) -> dict:
    """Parse a TS file's content (with comments stripped)."""
    content = re.sub(r"^\s*//.*$", "", content, flags=re.MULTILINE)
    m = re.search(r"=\s*\{", content)
    if not m:
        return {}
    start = m.end() - 1
    end = content.rfind("};")
    if end == -1:
        return {}
    obj_str = content[start:end + 1]
    try:
        return eval("(" + obj_str + ")")
    except Exception as e:
        print(f"  ⚠️ Failed to parse: {e}")
        return {}

def load_from_git(lang_code: str) -> dict:
    """Load the previous version of <code>.ts from git HEAD."""
    result = subprocess.run(
        ["git", "show", f"HEAD:src/lib/i18n/{lang_code}.ts"],
        capture_output=True,
        text=True,
        cwd="/home/z/my-project",
    )
    if result.returncode != 0:
        print(f"  ⚠️ git show failed for {lang_code}: {result.stderr[:200]}")
        return {}
    return load_strings_from_text(result.stdout)

def main():
    print("Loading English base...")
    en = load_strings_from_text(EN_FILE.read_text())
    print(f"  English: {len(en)} keys\n")

    for code in LANGS:
        # Get old translations from git
        old = load_from_git(code)
        # Also load the current file (might have newer translations)
        current_file = ROOT / f"{code}.ts"
        if current_file.exists():
            current = load_strings_from_text(current_file.read_text())
        else:
            current = {}

        # Merge: prefer current > old > English fallback
        merged = {}
        for key, en_value in en.items():
            if key in current and current[key]:
                merged[key] = current[key]
            elif key in old and old[key]:
                merged[key] = old[key]
            else:
                merged[key] = en_value

        # Count how many are translated (non-English)
        translated_count = sum(1 for k in en if k in merged and merged[k] != en[k])
        fallback_count = len(en) - translated_count

        # Write back to file
        json_str = json.dumps(merged, indent=2, ensure_ascii=False)
        content = f"""// Auto-generated translations for {code}.
// Generated by scripts/merge-i18n.py — DO NOT EDIT BY HAND.
//
// Some strings fall back to English where the AI translation hasn't
// been generated yet. To backfill, re-run scripts/translate-i18n.ts

export const {code}: Record<string, string> = {json_str};

export default {code};
"""
        current_file.write_text(content)
        pct = (translated_count / len(en)) * 100
        print(f"  {code}: {translated_count}/{len(en)} translated ({pct:.0f}%), {fallback_count} English fallbacks")

    print("\n✅ All language files now have all 410 keys.")

if __name__ == "__main__":
    main()
