#!/usr/bin/env python3
"""Merge existing partial translations with the new English base.
For each language:
  - Load existing translation file (159 strings)
  - Load new English file (410 strings)
  - For each key in English:
    - If translation exists in the language file → keep it
    - If missing → fall back to English value

This ensures every language file has all 410 keys (no key returns the
key string itself, which is bad UX). The fallback makes the app fully
functional in all languages immediately, even before backfilling.
"""
from pathlib import Path
import re

ROOT = Path("/home/z/my-project/src/lib/i18n")
EN_FILE = ROOT / "en.ts"
LANGS = ["hi", "bn", "te", "mr", "ta", "gu", "ur", "kn", "or", "ml", "pa", "as"]

def load_strings(path: Path) -> dict:
    """Parse a TS file with `export const xx: Record<string, string> = {...}`"""
    content = path.read_text()
    # Strip line comments (// ...) before parsing
    content = re.sub(r"^\s*//.*$", "", content, flags=re.MULTILINE)
    # Find the object literal between first `{` after `=` and last `};`
    m = re.search(r"=\s*\{", content)
    if not m:
        return {}
    start = m.end() - 1  # position of `{`
    end = content.rfind("};")
    if end == -1:
        return {}
    obj_str = content[start:end + 1]
    try:
        return eval("(" + obj_str + ")")
    except Exception as e:
        print(f"  ⚠️ Failed to parse {path.name}: {e}")
        return {}

def format_as_ts(obj: dict, lang_code: str) -> str:
    return f"""// Auto-generated translations for {lang_code}.
// Generated by scripts/merge-i18n.py — DO NOT EDIT BY HAND.
//
// NOTE: This file contains a mix of:
//   - Fully translated strings (from earlier AI translation run)
//   - English fallbacks for keys added later (marked with [EN] comment)
//
// To translate the [EN] fallbacks, re-run scripts/translate-i18n.ts

export const {lang_code}: Record<string, string> = {repr(obj).replace("'", '"').replace('\\n', '\\n').replace('\\"', '"')};

export default {lang_code};
"""

def format_as_ts_pretty(obj: dict, lang_code: str) -> str:
    """Pretty-print as TS with 2-space indent"""
    import json
    json_str = json.dumps(obj, indent=2, ensure_ascii=False)
    return f"""// Auto-generated translations for {lang_code}.
// Generated by scripts/merge-i18n.py — DO NOT EDIT BY HAND.
//
// NOTE: Some strings may fall back to English if the AI translation
// didn't cover them yet. To backfill, re-run scripts/translate-i18n.ts

export const {lang_code}: Record<string, string> = {json_str};

export default {lang_code};
"""

def main():
    print("Loading English base...")
    en = load_strings(EN_FILE)
    print(f"  English: {len(en)} keys\n")

    for code in LANGS:
        lang_file = ROOT / f"{code}.ts"
        if not lang_file.exists():
            print(f"  ⚠️ {code}.ts missing — skipping")
            continue

        existing = load_strings(lang_file)
        merged = {}
        fallback_count = 0
        translated_count = 0
        for key, en_value in en.items():
            if key in existing and existing[key]:
                merged[key] = existing[key]
                translated_count += 1
            else:
                merged[key] = en_value  # fallback to English
                fallback_count += 1

        lang_file.write_text(format_as_ts_pretty(merged, code))
        pct = (translated_count / len(en)) * 100
        print(f"  {code}: {translated_count}/{len(en)} translated ({pct:.0f}%), {fallback_count} English fallbacks")

    print("\n✅ All language files now have all 410 keys.")

if __name__ == "__main__":
    main()
