// Translate src/lib/i18n/en.ts into each major Indian language using the
// z-ai-web-dev-sdk chat completions API. Chunks the strings to avoid
// hitting the model's output token limit.

import ZAI from "z-ai-web-dev-sdk";
import { promises as fs } from "fs";
import * as path from "path";

const ROOT = "/home/z/my-project";
const EN_PATH = path.join(ROOT, "src/lib/i18n/en.ts");
const CHUNK_SIZE = 20; // strings per request — keeps output under token limit

type Lang = { code: string; name: string };

const TARGET_LANGUAGES: Lang[] = [
  { code: "hi", name: "Hindi (Devanagari)" },
  { code: "bn", name: "Bengali" },
  { code: "te", name: "Telugu" },
  { code: "mr", name: "Marathi" },
  { code: "ta", name: "Tamil" },
  { code: "gu", name: "Gujarati" },
  { code: "ur", name: "Urdu (Nastaliq)" },
  { code: "kn", name: "Kannada" },
  { code: "or", name: "Odia" },
  { code: "ml", name: "Malayalam" },
  { code: "pa", name: "Punjabi (Gurmukhi)" },
  { code: "as", name: "Assamese" },
];

async function loadEnglishStrings(): Promise<Record<string, string>> {
  const file = await fs.readFile(EN_PATH, "utf-8");
  const startIdx = file.indexOf("export const en: Record<string, string> = {");
  if (startIdx === -1) throw new Error("Couldn't find en export in en.ts");
  const objStart = file.indexOf("{", startIdx);
  const objEnd = file.lastIndexOf("};");
  const objSource = file.slice(objStart, objEnd + 1).replace(/;$/, "");
  // eslint-disable-next-line no-eval
  const obj = eval("(" + objSource + ")");
  return obj as Record<string, string>;
}

function chunkObject(obj: Record<string, string>, size: number): Record<string, string>[] {
  const keys = Object.keys(obj);
  const chunks: Record<string, string>[] = [];
  for (let i = 0; i < keys.length; i += size) {
    const slice: Record<string, string> = {};
    for (const k of keys.slice(i, i + size)) slice[k] = obj[k];
    chunks.push(slice);
  }
  return chunks;
}

function buildPrompt(strings: Record<string, string>, langName: string): string {
  return `You are a professional translator for ${langName}, used in a Christian faith-based web app called "Believ" (tagline: "Believe. Connect. Grow.").

The app serves Christians in India and includes:
- Bible reading, Bible trivia quizzes
- Church directory
- Marketplace for Christian products
- Prayer wall
- Faith Points (a virtual rewards system, "FP" is the abbreviation)

TASK: Translate every string VALUE in the JSON below from English to ${langName}. Keep all KEYS exactly as-is. Keep the {placeholder} syntax intact (e.g. {points}, {title}, {variations}, {amount}, {percent}, {count}). Keep brand names like "Believ", "Google", "WhatsApp", "KJV", "WEB" untranslated. Keep "FP" as "FP".

CRITICAL RULES:
1. Return ONLY a valid JSON object, no markdown, no commentary, no code fences.
2. Use natural, fluent ${langName} — not literal word-for-word translation. Use respectful Christian-friendly tone.
3. If a value contains HTML-like markup or special chars, preserve them.
4. For numbers in placeholders like "{points} more FP" or "{count} options", keep the placeholder in the right grammatical position for the target language.
5. For the app name "Believ" — keep it as "Believ" (don't transliterate).
6. For UI labels that are typically kept in English in Indian tech apps (like "Email", "Cart", "FP"), you may keep them in English OR translate naturally — choose what feels most natural for ${langName} speakers.

JSON to translate (this is chunk {CHUNK_NUM}):
${JSON.stringify(strings, null, 2)}

Return the translated JSON (no markdown, no code fences):`;
}

async function translateChunk(
  zai: Awaited<ReturnType<typeof ZAI.create>>,
  strings: Record<string, string>,
  lang: Lang,
  chunkNum: number,
  totalChunks: number
): Promise<Record<string, string>> {
  const prompt = buildPrompt(strings, lang.name);

  // Hard timeout — abort after 60s if API doesn't respond
  const timeoutMs = 60000;
  const timeoutPromise = new Promise<never>((_, reject) =>
    setTimeout(() => reject(new Error(`API timeout after ${timeoutMs}ms`)), timeoutMs)
  );

  const completion = await Promise.race([
    zai.chat.completions.create({
      messages: [
        { role: "user", content: prompt }
      ],
      thinking: { type: "disabled" },
    }),
    timeoutPromise,
  ]);

  const raw = completion.choices[0]?.message?.content?.trim() ?? "";
  const cleaned = raw.replace(/^```(?:json)?\s*/i, "").replace(/\s*```\s*$/i, "");

  try {
    const parsed = JSON.parse(cleaned);
    return parsed as Record<string, string>;
  } catch (e) {
    throw new Error(
      `[${lang.code} chunk ${chunkNum}/${totalChunks}] Failed to parse JSON: ${(e as Error).message}\nFirst 400 chars:\n${cleaned.slice(0, 400)}`
    );
  }
}

function formatAsTS(obj: Record<string, string>, langCode: string): string {
  return `// Auto-generated translations for ${langCode}.
// Generated by scripts/translate-i18n.ts — DO NOT EDIT BY HAND.
// To regenerate: bunx tsx scripts/translate-i18n.ts

export const ${langCode}: Record<string, string> = ${JSON.stringify(obj, null, 2)};

export default ${langCode};
`;
}

async function main() {
  console.log("Loading English base strings...");
  const en = await loadEnglishStrings();
  console.log(`✅ Loaded ${Object.keys(en).length} strings from en.ts`);

  console.log("\nInitializing ZAI SDK...");
  const zai = await ZAI.create();

  const outDir = path.join(ROOT, "src/lib/i18n");
  await fs.mkdir(outDir, { recursive: true });

  let success = 0;
  let failed = 0;
  for (const lang of TARGET_LANGUAGES) {
    console.log(`\n${"=".repeat(60)}`);
    console.log(`→ Translating to ${lang.name} (${lang.code})`);

    const chunks = chunkObject(en, CHUNK_SIZE);
    console.log(`   Split into ${chunks.length} chunks of ~${CHUNK_SIZE} strings each`);

    const merged: Record<string, string> = {};
    let langFailed = false;
    for (let i = 0; i < chunks.length; i++) {
      process.stdout.write(`   chunk ${i + 1}/${chunks.length}... `);
      // Retry each chunk up to 3 times
      let chunk: Record<string, string> | null = null;
      for (let attempt = 1; attempt <= 3; attempt++) {
        try {
          chunk = await translateChunk(zai, chunks[i], lang, i + 1, chunks.length);
          break;
        } catch (e) {
          if (attempt < 3) {
            process.stdout.write(`(retry ${attempt}) `);
            await new Promise((r) => setTimeout(r, 1500 * attempt));
          } else {
            process.stdout.write(`❌\n`);
            console.error(`   ${(e as Error).message}`);
            langFailed = true;
          }
        }
      }
      if (!chunk) break;
      const keysTranslated = Object.keys(chunk).length;
      process.stdout.write(`✅ ${keysTranslated} strings\n`);
      Object.assign(merged, chunk);
      // Larger delay between requests to avoid rate limiting (429)
      await new Promise((r) => setTimeout(r, 2000));
    }

    if (langFailed) {
      console.log(`❌ ${lang.code} failed — not writing file`);
      failed++;
      continue;
    }

    const keysEn = Object.keys(en).length;
    const keysMerged = Object.keys(merged).length;
    if (keysMerged < keysEn * 0.95) {
      console.warn(`   ⚠️  Only ${keysMerged}/${keysEn} strings translated`);
    } else {
      console.log(`   ✅ ${keysMerged}/${keysEn} strings translated`);
    }
    const outPath = path.join(outDir, `${lang.code}.ts`);
    await fs.writeFile(outPath, formatAsTS(merged, lang.code));
    console.log(`   📝 Written to ${outPath}`);
    success++;
  }

  console.log(`\n${"=".repeat(60)}`);
  console.log(`Done. ${success} succeeded, ${failed} failed.`);
}

main().catch((e) => {
  console.error("Fatal error:", e);
  process.exit(1);
});
