// Translate ONLY the missing keys in each language file (backfill mode).
// Loads existing translations, finds keys that are still English fallbacks,
// translates them in chunks, and writes back.
//
// This is rate-limit-friendly: only translates what's missing.

import ZAI from "z-ai-web-dev-sdk";
import { promises as fs } from "fs";
import * as path from "path";
import * as re from "re"; // not needed but to suppress TS warning

const ROOT = "/home/z/my-project";
const EN_PATH = path.join(ROOT, "src/lib/i18n/en.ts");
const CHUNK_SIZE = 20; // strings per request
const DELAY_MS = 2000; // delay between requests to avoid 429

type Lang = { code: string; name: string };

const TARGET_LANGUAGES: Lang[] = [
  { code: "bn", name: "Bengali" },  // 45% done, missing 187
  { code: "te", name: "Telugu" },   // 45% done
  { code: "mr", name: "Marathi" },
  { code: "ta", name: "Tamil" },
  { code: "gu", name: "Gujarati" },
  { code: "ur", name: "Urdu (Nastaliq)" },
  { code: "kn", name: "Kannada" },
  { code: "or", name: "Odia" },
  { code: "ml", name: "Malayalam" },
  { code: "pa", name: "Punjabi (Gurmukhi)" },
  { code: "as", name: "Assamese" },
  { code: "hi", name: "Hindi (Devanagari)" },  // 45% done, missing 187
];

async function loadStrings(filePath: string): Promise<Record<string, string>> {
  const file = await fs.readFile(filePath, "utf-8");
  // Strip line comments
  const stripped = file.replace(/^\s*\/\/.*$/gm, "");
  const m = stripped.match(/=\s*\{/);
  if (!m) return {};
  const start = m.index! + m[0].length - 1;
  const end = stripped.lastIndexOf("};");
  if (end === -1) return {};
  const objStr = stripped.slice(start, end + 1);
  // eslint-disable-next-line no-eval
  return eval("(" + objStr + ")");
}

function buildPrompt(strings: Record<string, string>, langName: string): string {
  return `You are a professional translator for ${langName}, used in a Christian faith-based web app called "Believ" (tagline: "Believe. Connect. Grow.").

The app serves Christians in India and includes Bible trivia, church directory, marketplace, prayer wall, and Faith Points (rewards).

TASK: Translate every string VALUE in the JSON below from English to ${langName}. Keep all KEYS as-is. Keep {placeholder} syntax intact. Keep brand names like "Believ", "Google", "WhatsApp", "KJV", "WEB", "FP" untranslated.

RULES:
1. Return ONLY valid JSON (no markdown, no code fences).
2. Use natural, fluent ${langName}. Respectful Christian-friendly tone.
3. For UI labels typically kept in English (Email, Cart, FP), you may keep them in English or translate naturally.

JSON to translate:
${JSON.stringify(strings, null, 2)}

Return the translated JSON:`;
}

async function translateChunk(
  zai: Awaited<ReturnType<typeof ZAI.create>>,
  strings: Record<string, string>,
  lang: Lang
): Promise<Record<string, string>> {
  const prompt = buildPrompt(strings, lang.name);

  const timeoutMs = 90000;
  const timeoutPromise = new Promise<never>((_, reject) =>
    setTimeout(() => reject(new Error(`API timeout after ${timeoutMs}ms`)), timeoutMs)
  );

  const completion = await Promise.race([
    zai.chat.completions.create({
      messages: [{ role: "user", content: prompt }],
      thinking: { type: "disabled" },
    }),
    timeoutPromise,
  ]);

  const raw = completion.choices[0]?.message?.content?.trim() ?? "";
  const cleaned = raw.replace(/^```(?:json)?\s*/i, "").replace(/\s*```\s*$/i, "");

  return JSON.parse(cleaned);
}

function formatAsTS(obj: Record<string, string>, langCode: string): string {
  return `// Auto-generated translations for ${langCode}.
// Generated by scripts/translate-missing-i18n.ts — DO NOT EDIT BY HAND.

export const ${langCode}: Record<string, string> = ${JSON.stringify(obj, null, 2)};

export default ${langCode};
`;
}

function chunkObject(obj: Record<string, string>, size: number): Record<string, string>[] {
  const keys = Object.keys(obj);
  const chunks: Record<string, string>[] = [];
  for (let i = 0; i < keys.length; i += size) {
    const slice: Record<string, string> = {};
    for (const k of keys.slice(i, i + size)) slice[k] = obj[k];
    chunks.push(slice);
  }
  return chunks;
}

async function main() {
  console.log("Loading English base...");
  const en = await loadStrings(EN_PATH);
  console.log(`  English: ${Object.keys(en).length} keys\n`);

  console.log("Initializing ZAI SDK...");
  const zai = await ZAI.create();

  const outDir = path.join(ROOT, "src/lib/i18n");

  let totalSuccess = 0;
  let totalFailed = 0;
  for (const lang of TARGET_LANGUAGES) {
    console.log(`\n${"=".repeat(60)}`);
    console.log(`→ Backfilling ${lang.name} (${lang.code})`);

    const langFile = path.join(outDir, `${lang.code}.ts`);
    const existing = await loadStrings(langFile);

    // Find missing keys (where current value equals English value = fallback)
    const missing: Record<string, string> = {};
    for (const [key, enVal] of Object.entries(en)) {
      if (!existing[key] || existing[key] === enVal) {
        missing[key] = enVal;
      }
    }

    if (Object.keys(missing).length === 0) {
      console.log(`  ✅ Already fully translated — skipping`);
      continue;
    }

    console.log(`  Missing: ${Object.keys(missing).length} strings`);
    const chunks = chunkObject(missing, CHUNK_SIZE);
    console.log(`  Split into ${chunks.length} chunks of ~${CHUNK_SIZE} strings each`);

    let langFailed = false;
    for (let i = 0; i < chunks.length; i++) {
      process.stdout.write(`  chunk ${i + 1}/${chunks.length}... `);
      let chunk: Record<string, string> | null = null;
      for (let attempt = 1; attempt <= 3; attempt++) {
        try {
          chunk = await translateChunk(zai, chunks[i], lang);
          break;
        } catch (e) {
          if (attempt < 3) {
            process.stdout.write(`(retry ${attempt}) `);
            await new Promise((r) => setTimeout(r, 3000 * attempt));
          } else {
            process.stdout.write(`❌\n`);
            console.error(`  ${(e as Error).message}`);
            langFailed = true;
          }
        }
      }
      if (!chunk) break;
      process.stdout.write(`✅ ${Object.keys(chunk).length} strings\n`);
      // Merge translated chunk into existing
      Object.assign(existing, chunk);
      // Save after each chunk so progress isn't lost
      await fs.writeFile(langFile, formatAsTS(existing, lang.code));
      await new Promise((r) => setTimeout(r, DELAY_MS));
    }

    if (langFailed) {
      console.log(`❌ ${lang.code} partially failed — saved ${Object.keys(existing).length} strings`);
      totalFailed++;
    } else {
      console.log(`✅ ${lang.code} complete — ${Object.keys(existing).length} strings`);
      totalSuccess++;
    }
  }

  console.log(`\n${"=".repeat(60)}`);
  console.log(`Done. ${totalSuccess} fully succeeded, ${totalFailed} partially failed.`);
}

main().catch((e) => {
  console.error("Fatal error:", e);
  process.exit(1);
});
